### ISSUE TITLE
Ninja build fails

### ISSUE THREAD

**Issue by vadi2** [gdraheim/zziplib#106]
```
[main] Building folder: zziplib-0.13.71 libzzip
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/vadi/Downloads/zziplib-0.13.71/build --config Debug --target libzzip -- -j 6
[build] ninja: error: build.ninja:1885: bad $-escape (literal $ must be written as $$)
[build] 
[build] Build finished with exit code 1
```

`build.ninja:1885` is:

```
  COMMAND = cd /home/vadi/Downloads/zziplib-0.13.71/build/docs && /bin/bash -c "ls -l /home/vadi/Downloads/zziplib-0.13.71/build/docs/site.html" && /bin/bash -c "mkdir -vp $(DESTDIR)/usr/local/share/doc/zziplib  >&2 || ls -ld $(DESTDIR)/usr/local/share/doc/zziplib >&2" && /bin/bash -c "cd /home/vadi/Downloads/zziplib-0.13.71/build/docs && cp zziplib.html zzipmmapped.html zzipfseeko.html $(DESTDIR)/usr/local/share/doc/zziplib/" && /bin/bash -c "cd /home/vadi/Downloads/zziplib-0.13.71/docs && cp README.* COPYING.* $(DESTDIR)/usr/local/share/doc/zziplib/" && /bin/bash -c "cd /home/vadi/Downloads/zziplib-0.13.71 && cp ChangeLog          $(DESTDIR)/usr/local/share/doc/zziplib/" && /bin/bash -c "cd /home/vadi/Downloads/zziplib-0.13.71 && cp /home/vadi/Downloads/zziplib-0.13.71/bins/zzdir.c /home/vadi/Downloads/zziplib-0.13.71/bins/zzcat.c /home/vadi/Downloads/zziplib-0.13.71/bins/zzobfuscated.c /home/vadi/Downloads/zziplib-0.13.71/bins/zziptest.c /home/vadi/Downloads/zziplib-0.13.71/bins/zzxordir.c /home/vadi/Downloads/zziplib-0.13.71/bins/zzxorcat.c /home/vadi/Downloads/zziplib-0.13.71/bins/zzxorcopy.c  $(DESTDIR)/usr/local/share/doc/zziplib/" && /bin/bash -c "cd /home/vadi/Downloads/zziplib-0.13.71 && cp /home/vadi/Downloads/zziplib-0.13.71/SDL/SDL_rwops_zzcat.c /home/vadi/Downloads/zziplib-0.13.71/SDL/SDL_rwops_zzip.c /home/vadi/Downloads/zziplib-0.13.71/SDL/SDL_rwops_zzip.h  $(DESTDIR)/usr/local/share/doc/zziplib/" && /bin/bash -c "cd $(DESTDIR)/usr/local/share/doc/zziplib && cp /home/vadi/Downloads/zziplib-0.13.71/build/docs/*.html ." && /bin/bash -c "cd $(DESTDIR)/usr/local/share/doc/zziplib && ln -s zzip-index.html index.html"
```

**Comment by gdraheim** [comment]
It works for me - when looking at the bad command I can see some "$(DESTDIR)" references which I can not find in the current source code on github. So it may have been fixed earlier (but I did not have time to make a release).

Now the command looks like this

`build-nj/build.ninja:  COMMAND = cd /home/guidod/work/zziplib-master/build-nj/docs && /bin/bash -c "ls -l /home/guidod/work/zziplib-master/build-nj/docs/site.html" && /bin/bash -c "mkdir -vp \$$DESTDIR/home/guidod/local/share/doc/zziplib  >&2 || ls -ld \$$DESTDIR/home/guidod/local/share/doc/zziplib >&2" && /bin/bash -c "cd /home/guidod/work/zziplib-master/build-nj/docs && cp zziplib.html zzipmmapped.html zzipfseeko.html \$$DESTDIR/home/guidod/local/share/doc/zziplib/" && /bin/bash -c "cd /home/guidod/work/zziplib-master/docs && cp README.* COPYING.* \$$DESTDIR/home/guidod/local/share/doc/zziplib/" && /bin/bash -c "cd /home/guidod/work/zziplib-master && cp ChangeLog          \$$DESTDIR/home/guidod/local/share/doc/zziplib/" && /bin/bash -c "cd /home/guidod/work/zziplib-master && cp /home/guidod/work/zziplib-master/bins/zzdir.c /home/guidod/work/zziplib-master/bins/zzcat.c /home/guidod/work/zziplib-master/bins/zzobfuscated.c /home/guidod/work/zziplib-master/bins/zziptest.c /home/guidod/work/zziplib-master/bins/zzxordir.c /home/guidod/work/zziplib-master/bins/zzxorcat.c /home/guidod/work/zziplib-master/bins/zzxorcopy.c  \$$DESTDIR/home/guidod/local/share/doc/zziplib/" && /bin/bash -c "cd /home/guidod/work/zziplib-master && cp /home/guidod/work/zziplib-master/SDL/SDL_rwops_zzcat.c /home/guidod/work/zziplib-master/SDL/SDL_rwops_zzip.c /home/guidod/work/zziplib-master/SDL/SDL_rwops_zzip.h  \$$DESTDIR/home/guidod/local/share/doc/zziplib/" && /bin/bash -c "cd \$$DESTDIR/home/guidod/local/share/doc/zziplib && cp /home/guidod/work/zziplib-master/build-nj/docs/*.html ." && /bin/bash -c "cd \$$DESTDIR/home/guidod/local/share/doc/zziplib && ln -s zzip-index.html index.html"
build-nj/build.ninja:  COMMAND = cd /home/guidod/work/zziplib-master/build-nj/docs && /bin/bash -c "ls -l /home/guidod/work/zziplib-master/build-nj/docs/*pages.tar" && /bin/bash -c "mkdir -vp \$$DESTDIR/home/guidod/local/share/doc/zziplib  >&2 || ls -ld \$$DESTDIR/home/guidod/local/share/doc/zziplib >&2" && /bin/bash -c "cd \$$DESTDIR/home/guidod/local/share/doc/zziplib && tar x -f /home/guidod/work/zziplib-master/build-nj/docs/htmpages.tar" && /bin/bash -c "cd \$$DESTDIR/home/guidod/local/share/doc/zziplib && mv html man"
build-nj/build.ninja:  COMMAND = cd /home/guidod/work/zziplib-master/build-nj/docs && /bin/bash -c "ls -l /home/guidod/work/zziplib-master/build-nj/docs/*pages.tar" && /bin/bash -c "mkdir -vp \$$DESTDIR/home/guidod/local/share/man  >&2 || ls -ld \$$DESTDIR/home/guidod/local/share/man >&2" && /bin/bash -c "cd \$$DESTDIR/home/guidod/local/share/man && tar xf /home/guidod/work/zziplib-master/build-nj/docs/manpages.tar"
`
