### ISSUE TITLE
Use portable switches for `ln`

### ISSUE THREAD

**Issue by jurajlutter** [gdraheim/zziplib#111]
On platforms (SystemV-derived, like illumos or SmartOS), there is no `-v` flag for `ln`, causing the build to fail. The solution is to not use `-v`.

**Comment by gdraheim** [comment]
Please check the 'develop' branch where I have extended the cmake checks looking for "ln -verbose".

I will cherry-pick that to the master branch if it fixes your problem.

Thanks in advance.

**Comment by jurajlutter** [comment]
FWIW, my proposed patch for pkgsrc is:

https://pkgsrc-smartos.wilbury.net/patches/NetBSD/archivers_zziplib.diff

this also addresses a problem on Darwin.

**Comment by jurajlutter** [comment]
@gdraheim works.

**Comment by gdraheim** [comment]
Thanks for pointing out that the implementation is required in zzipwrap/cmake as well.

I have added it there, and both patches were cherry-picked to to /master

**Comment by gdraheim** [comment]
You had also mentioned a problem on Darwin but I don't see a difference over the current branches. I guess I can close it here.
