### ISSUE TITLE
Out-of-date homepage

### ISSUE THREAD

**Issue by jwilk** [gdraheim/zziplib#13]
README says:

>The zziplib project is hosted at SourceForge, the complete documentation can be found at http://zziplib.sf.net

But http://zziplib.sf.net hasn't been updated for years. For example:
* The top-level corner mentions version 0.13.58, released in 2009-09-24.
* Last ChangeLog entry is from 2009-08-23.
* *Developer Area* points to Subversion repository which had last commit in 2013-11-06.

**Comment by gdraheim** [comment]
done some updates to the documentation

**Comment by gdraheim** [comment]
the pages of https://zziplib.sf.net have been updated with a prominent marker back to github.
