### ISSUE TITLE
CMake project doesn't export targets

### ISSUE THREAD

**Issue by vividos** [gdraheim/zziplib#134]
I'm trying to include zziplib into my project using vcpkg and like to use `find_package(zziplib REQUIRED)` to automatically configure includes and libs. Unfortunately that fails, and according to vcpkg folks, the only missing thing is that in `zzip/CMakeFiles.txt`, the project doesn't export its targets. See also my issue I opened in vcpkg project: https://github.com/microsoft/vcpkg/issues/25186

From reading CMake documentation I gather that these lines should be changed:

https://github.com/gdraheim/zziplib/blob/ec0364a245d869a509481d80fc19c70cf945cee7/zzip/CMakeLists.txt#L263-L266
The lines could look like this:

    install(TARGETS libzzip 
        EXPORT libzzip
        RUNTIME ...

What do you think? Could the line be added?

**Comment by Osyotr** [comment]
Not exactly a one line change, but still pretty straightforward:
```cmake
install(TARGETS libzzip 
    EXPORT libzzipConfig # note Config suffix
    RUNTIME ...
)
```
And then install config files:
```cmake
install(EXPORT libzippConfig
    NAMESPACE libzipp::
    DESTINATION share/libzipp
)
```

This should be done for each target that needs to be exported.

**Comment by vividos** [comment]
Thanks Osyotr for the details!

**Comment by gdraheim** [comment]
Looks interesting, I did not know that cmake has its own library export format. I can not really support the solution but I hope you keep an eye on it.
