### ISSUE TITLE
Errors when building for macOS

### ISSUE THREAD

**Issue by wolfv** [gdraheim/zziplib#153]
Trying to build the latest `zziplib` for macOS gives some errros about pointer conversions:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=886344&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b

I thought you might be interested :)

**Comment by gdraheim** [comment]
"file->zlib.next = offset;" is already fixed on develop. It does now read "file->zlib.next = start".

It's based on a hack that was once merged but I started to deactivate the problematic code section. Currently doing some tests.

**Comment by gdraheim** [comment]
I have been busy fixing all the bugs that were still around. Actually, I did intend to bring out a release before making functional changes. However, after completion I am quite confident that it works in general, so I am going to put out another release today.

**Comment by wolfv** [comment]
Great! Will try to update the package then :)

**Comment by wolfv** [comment]
Cool, the issues on macOS are fixed. Now only MSVC seems to be missing some defines? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=888498&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc

**Comment by ryandesign** [comment]
> Cool, the issues on macOS are fixed.

Then maybe this issue should be closed and you can file a new issue for the new problem?
