### ISSUE TITLE
Full source code path printed by --version flag

### ISSUE THREAD

**Issue by ryandesign** [gdraheim/zziplib#156]
Using the `--version` flag on `zzcat` or other utilities installed by zziplib, the full path to the source code file that was used to build that utility is printed:

```
% zzcat --version       
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_archivers_libzzip/libzzip/work/zziplib-0.13.72/bins/zzcat.c version zziplib 0.13.72
```

The program may have been compiled on a different computer, so these paths are not useful to the user and should not be printed.

**Comment by gdraheim** [comment]
interesting. :+1:

**Comment by gdraheim** [comment]
added some wrapper for the print
