### ISSUE TITLE
Coverage tools are unconditionally required?

### ISSUE THREAD

**Issue by wolfv** [gdraheim/zziplib#167]
The comment in CodeCoverage.cmake says:

```
# 2. Add the following line to your CMakeLists.txt (best inside an if-condition
#    using a CMake option() to enable it just optionally):
#      include(CodeCoverage)
```

Unfortunately, I can't find a CMake option to turn it off. That makes redistribution harder than it should be :)

Can we add a option?

**Comment by gdraheim** [comment]
Perhaps a duplicate with 081b8ba4d0417abe6c2d997f5198e23b7fdb2977

**Comment by wolfv** [comment]
yep - sorry i didn't see that due to the master branch being the default.
