### ISSUE TITLE
`cp -s` is not portable

### ISSUE THREAD

**Issue by mojca** [gdraheim/zziplib#31]
`make check` fails on macOS due to unportable [cp -s](https://github.com/gdraheim/zziplib/blob/e37c80966bd7ef16893dcd2caf1b85ae89df0aa7/test/Makefile.am#L48). What about using `ln -s`?

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/cp.1.html

**Comment by mojca** [comment]
Besides that it would help if `python` one line below was not hardcoded directly, but rather used as a `$(PYTHON)` variable.

**Comment by gdraheim** [comment]
The usage of `"cp -s $file ."` can be replaced by `"ln -s $file . | cp $file ."`

**Comment by mojca** [comment]
Thanks for both patches. Looks good. (Are there indeed cases when `ln -s` is not available?)

**Comment by gdraheim** [comment]
Well, the filesystem needs to support that special file kind - only the unix'ish ones do have it always. Even ntfs may have its problems about it (although the latest unix-wrappers should be able to use the fstype feature).

**Comment by gdraheim** [comment]
done.
