### ISSUE TITLE
Please switch to a newer version of autotools

### ISSUE THREAD

**Issue by mojca** [gdraheim/zziplib#32]
Do you have any option to generate the files with a newer version of autotools?

One particular problem is the following patch that we need in MacPorts in order to properly differentiate macOS 10.10 from 10.1:
```patch
--- configure.orig
+++ configure
@@ -7445,7 +7445,7 @@
       case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
 	10.0,*86*-darwin8*|10.0,*-darwin[91]*)
 	  _lt_dar_allow_undefined='${wl}-undefined ${wl}dynamic_lookup' ;;
-	10.[012]*)
+	10.[012][,.]*)
 	  _lt_dar_allow_undefined='${wl}-flat_namespace ${wl}-undefined ${wl}suppress' ;;
 	10.*)
 	  _lt_dar_allow_undefined='${wl}-undefined ${wl}dynamic_lookup' ;;
```
Those changes come for free with newer versions (not sure since when though).

Also, `configure` complains about
```
configure: line 15012: aclocal-1.13: command not found
```
Apart from version 1.13 being old: why would `aclocal` be called during `configure`? Shouldn't it be called upfront/before?

**Comment by gdraheim** [comment]
aclocal-1.13 is part of automake-1.13

    
    > LANG=C sudo zypper update automake
    Loading repository data...
    Reading installed packages...
    No update candidate for 'automake-1.13.4-10.15.noarch'. The highest available version is already installed.
    Resolving package dependencies...
    
    Nothing to do.

 cat /etc/issue
Welcome to openSUSE Leap 42.3 - Kernel \r (\l).

**Comment by gdraheim** [comment]
Tumbleweed / openSUSE Leap 15.0 will ship with 1.15.1

https://software.opensuse.org/package/automake

**Comment by mojca** [comment]
Version 1.13 has been released in 2012. That's more than five years old and doesn't support any supported version of macOS any longer :(

Yosemite where their regexp breaks was released in 2014 and is no longer supported.

OK, we'll keep patching the configure script a bit longer then.

**Comment by gdraheim** [comment]
I had to do some checks about the packager manager but in the end I have updated automake to the Tumbleweed version.

new autotools done.

**Comment by mojca** [comment]
Thanks for the patch, but there's another piece missing. Where does `m4/libtool.m4` come from? It looks like that one is outdated too.

**Comment by gdraheim** [comment]
```
zziplib> LANG=C zypper search -s libtool
Loading repository data...
Reading installed packages...

S | Name                | Type       | Version     | Arch   | Repository                        
--+---------------------+------------+-------------+--------+-----------------------------------
i | libtool             | package    | 2.4.2-22.1  | x86_64 | Hauptaktualisierungs-Repository   
v | libtool             | package    | 2.4.2-20.14 | x86_64 | Haupt-Repository (OSS)            
```

https://software.opensuse.org/package/libtool

Again, Tumbleweed is on 2.4.6

... I'll check for a download/update

**Comment by gdraheim** [comment]
new libtool done.

**Comment by gdraheim** [comment]
done.
