### ISSUE TITLE
circular #include for zzip32.h and lib.h

### ISSUE THREAD

**Issue by feiyunw** [gdraheim/zziplib#44]
In zzip\zzip32.h:
```
#ifndef _ZZIP_ZZIP32_H
#define _ZZIP_ZZIP32_H

#include <zzip/lib.h>
```
In zzip\lib.h
```
#ifndef _ZZIP_LIB_H /* zzip.h */
#define _ZZIP_LIB_H

#include <zzip/zzip.h>
#include <zzip/plugin.h>
#include <zzip/stdint.h>
#include <zzip/zzip32.h>
```
These header files include each other. It is not a good smell.

**Comment by gdraheim** [comment]
I have done a quick codesearch through public (opensource) repositories and it seems that no one has ever used the *32 functions explicitly. So I decided to cut that include out of `<zzip/lib.h>`.

**Comment by gdraheim** [comment]
done.
