### ISSUE TITLE
latest stable release version 0.13.68 or 0.13.69?

### ISSUE THREAD

**Issue by ilovezfs** [gdraheim/zziplib#45]
https://github.com/gdraheim/zziplib/releases
shows 0.13.69

https://sourceforge.net/projects/zziplib
shows 0.13.68

**Comment by gdraheim** [comment]
Github is main site for releases, not Sourceforge.

A hint on the last release uploaded at Sourceforge points to Github, what else should be done?

https://sourceforge.net/projects/zziplib/files/zziplib13/0.13.68/

**Comment by fxcoudert** [comment]
Possibly updating the sourceforge website to state that “Github is main site for releases, not Sourceforge” or “Newest releases are found on Github, above are older releases" or something to that extent. Right now it's not really clear indeed

**Comment by gdraheim** [comment]
I have updated the readme files and meta information at sourceforge.net.

Please review if that looks good enough to you. ;) 

Thank you in advance.

**Comment by gdraheim** [comment]
done.

**Comment by ilovezfs** [comment]
Thanks, @gdraheim!
