### ISSUE TITLE
docs/makedocs.py is not compatible with python3

### ISSUE THREAD

**Issue by mojca** [gdraheim/zziplib#47]
Python 2.7 has [less than two years to live](https://pythonclock.org). The `print` statements in `makedocs.py` are not compatible with python 3 yet, I assume the conversion should be pretty straightforward.

**Comment by gdraheim** [comment]
Actually, one can use `from __future__ import print_function` to ensure compatibility.

**Comment by mojca** [comment]
I usually don't even do that, I just make sure that I provide a single argument, as in
```python
print("something " + foo)
# or
print("something {}".format(foo))
```
instead of
```
print("something", foo)
```
Then you don't even need to import `print_function`, it just works.

**Comment by gdraheim** [comment]
Additionally there was a need to convert ET.tostring() to a real str() in python3.

done.

**Comment by gdraheim** [comment]
All parts are tested with python3 latetely.
