### ISSUE TITLE
zziptests.py don't return non-zero return code on errors and require network access

### ISSUE THREAD

**Issue by flokli** [gdraheim/zziplib#53]
While trying to enable running tests during the build process of the zzlib package in NixOS, I saw tests running through 'successfully' without a non-zero return code, but log showed a lot of tests were failing, due to missing network access in the sandboxed builder.

Can you have a look in why this error is not propagated?

And secondly, as the URLs being downloaded all seem to be POCs from other git repos: Is it possible to simply add these repositories as submodules, and not download them during test phase? This would really help for reproducibility :-)

**Comment by gdraheim** [comment]
Actually, you need to do something like this

    result = Runner(verbosity=opt.verbose).run(suite)
    if not result.wasSuccessful():
        sys.exit(1)

which I know from other projects. Added in the last release.

The other question is also raised in #24
