### ISSUE TITLE
missing defines

### ISSUE THREAD

**Issue by geromueller** [gdraheim/zziplib#6]
Hi,

when fnmatch is not available, FNM_NOESCAPE|FNM_PATHNAME|FNM_PERIOD are not defined aswell.

**Comment by gdraheim** [comment]
the <zzip/__fnmatch.h> header has been extended to conver the necessary defines that are used in bins/*.c

**Comment by mojca** [comment]
I now get
```
../../zziplib/bins/unzzipdir-zip.c:103:9: error: implicit declaration of function 'fnmatch' [-Werror=implicit-function-declaration]
   if (! fnmatch (argv[argn], name,
         ^~~~~~~
```

**Comment by gdraheim** [comment]
oh forgot about that one.... renamed to `_zzip_fnmatch`

**Comment by gdraheim** [comment]
done as well
