### ISSUE TITLE
zziplib-manpages.tar: No such file or directory

### ISSUE THREAD

**Issue by anatoli26** [gdraheim/zziplib#8]
During compilation of 13.67 release from GitHub on Ubuntu 16.04 I'm getting the following error:

```
test -s zziplib.docbook && mv zziplib.docbook zziplib.xml
: "unix man format of the manpages - goes to ../share/man/man3"
cp ../../docs/zziplib-manpages.tar manpages.tar
cp: cannot stat ‘../../docs/zziplib-manpages.tar’: No such file or directory
make[3]: *** [manpages.tar] Error 1

```

For some reason the release files on GitHub don't have `docs/zziplib-manpages.tar` file included. I had to copy it from the sourceforge 13.59 release to compile the library.

**Comment by gdraheim** [comment]
I have added a "make dist" on sourceforge files with 13.68 .... however that is only a temporary solution as the manpage.tar needs to be generated.

In the long run I would like to get rid of docbook / xmlto but that can take a while.

**Comment by gdraheim** [comment]
I have added a small converter dbk2man.py in order to allow to regenerate the manpages.tar even without xmlto. Since manpages.tar are always built from source there should be no error anymore.

**Comment by gdraheim** [comment]
done.

**Comment by anatoli26** [comment]
Thanks, builds fine now!
