### ISSUE TITLE
CMake produces a different output than Autotools

### ISSUE THREAD

**Issue by jtojnar** [gdraheim/zziplib#86]
* [x] Installs `include/SDL_rwops_zzip/SDL_rwops_zzip.{c,h}` even though SDL is not available.
* [ ] Misses `lib/pkgconfig/zzip-zlib-config.pc`
* [x] Misses compat symlinks for libzzip (bug in packaging, will open PR).
* [x] Misses compat symlinks for the rest of the packages
* [x] Incorrect version in pc file
* [x] Incorrect paths in pc file (will open PR)
* [x] Missing descriptions in pc file
* [x] Missing version value in the zzipwrap.pc

```patch
--- /nix/store/rp8igl3waqpcif9bx9g8fkjc2j2fc35p-zziplib-0.13.70/lib/pkgconfig/zziplib.pc
+++ /home/jtojnar/Projects/nixpkgs/result/lib/pkgconfig/zziplib.pc
@@ -1,18 +1,9 @@
-# generated by configure / remove this line to disable regeneration
-prefix=/nix/store/rp8igl3waqpcif9bx9g8fkjc2j2fc35p-zziplib-0.13.70
-exec_prefix=${prefix}
-bindir=${exec_prefix}/bin
-libdir=${exec_prefix}/lib
-datarootdir=${prefix}/share
-datadir=${datarootdir}
-sysconfdir=${prefix}/etc
-includedir=${prefix}/include
-package=zziplib
-suffix=
+prefix=/nix/store/3r66y89mxf35sp39imxwjnhr1kpqq971-zziplib-0.13.70
+libdir=${prefix}//nix/store/3r66y89mxf35sp39imxwjnhr1kpqq971-zziplib-0.13.70/lib
+includedir=${prefix}//nix/store/3r66y89mxf35sp39imxwjnhr1kpqq971-zziplib-0.13.70/include
 
 Name: zziplib
-Description: ZZipLib - libZ-based ZIP-access Library with an Easy-to-Use API
-Version: 0.13.70
-Requires: zzip-zlib-config
-Libs: -L${libdir}  -lzzip
-Cflags: -I${includedir} 
+Version: 0.13.69
+Requires: zlib
+Libs: -L${libdir} -lzzip
+Cflags: -I${includedir}
```

**Comment by gdraheim** [comment]
I was testing for compat symlinks quite heavily, so that makes me wonder about the details.

I'll check on the remaining parts asap.

**Comment by gdraheim** [comment]
Misses lib/pkgconfig/zzip-zlib-config.pc => I would like to drop that one. The current zziplib.pc has a q "Requires: zlib" now.

And zlib.pc is shipped with zlib now (it was not when I started to build this library).

    rpm -q --whatprovides /usr/lib64/pkgconfig/zlib.pc
    zlib-devel-1.2.11-lp151.4.1.x86_64
