### ISSUE TITLE
Manpage rendering is slightly borked

### ISSUE THREAD

**Issue by jtojnar** [gdraheim/zziplib#91]
I see lot of `\fIn` and `b'`:

![Screenshot from 2020-04-18 13-04-22](https://user-images.githubusercontent.com/705123/79636127-bec59d00-8175-11ea-8be0-f2379f30bb02.png)

**Comment by gdraheim** [comment]
Hahaha, thanks for the hint - it seems that the switch to python3 has made for some muck in the final page.

**Comment by gdraheim** [comment]
It seems that not only open(file) reads bytes but also the elem-tree of the xml-reader. I will decode that as utf-8 by now so that the final page gets encoded correctlly.

**Comment by jtojnar** [comment]
Can confirm this fixes the issue.
